### ISSUE TITLE
npm access to gulp-brotli

### ISSUE THREAD

**Issue by nstepien** [seznam/gulp-brotli#1]
If you want I can relinquish access to the `gulp-brotli` package name, so you can start using it instead, as I don't want to maintain my version anymore, and using Node's internal module makes more sense nowadays.
You'll have to publish it as a v2 I guess, to not break semver.

**Comment by jurca** [comment]
@MayhemYDG 

Hello and thank you for your kind offer.

I will consider it, however, I think you would agree that I should first implement the missing features (compared to your plugin):
- decompression support
- the `skipLarger` option

I'll try to look into those in the upcoming days and I'll let you know if I make any progress - it might take a couple of days or weeks.

**Comment by nstepien** [comment]
Sounds good to me.

**Comment by jurca** [comment]
@MayhemYDG Hello again, I've updated the plugin and the readme. Would be so kind and evaluate it, please? If I am to inherit your package's name, I would like to be worthy of it first :).

**Comment by nstepien** [comment]
LGTM, I've added you (`jurca` on npm) as maintainer for the `gulp-brotli` package now.

**Comment by jurca** [comment]
I'm afraid something did not work:

`npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/gulp-brotli - You do not have permission to publish "gulp-brotli". Are you logged in as the correct user?`

**Comment by jurca** [comment]
Could you try this? I have used this in the past and it worked fine:

https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account#transferring-a-package-from-a-user-account-to-another-user-account-on-the-command-line

**Comment by nstepien** [comment]
Did that now, try again. Make sure you're logged in as `jurca` with `npm whoami`.

**Comment by jurca** [comment]
I've check on the first error already, I'm logged in as `jurca`.

Here's what's suspicious:

```
$ npm owner ls gulp-brotli
mayhem <stepien.nicolas@gmail.com>
oohnoitz <oohnoitz@gmail.com>
```

I'm guessing npm is having some cache issues again, so I think I'll give it some time a try again tomorrow.

**Comment by nstepien** [comment]
I wonder if npm sends an invite that you can accept via email, maybe check that.

**Comment by jurca** [comment]
Already ahead of you, and nothing. Historically they did not do that either.

That being said...

```
$ npm owner ls gulp-brotli
mayhem <stepien.nicolas@gmail.com>
oohnoitz <oohnoitz@gmail.com>
jurca <mjurca@centrum.cz>
```

```
npm notice 
npm notice 📦  gulp-brotli@2.0.0
npm notice === Tarball Contents === 
npm notice 734B  LICENSE     
npm notice 3.3kB index.js    
npm notice 1.8kB package.json
npm notice 2.4kB index.js.map
npm notice 4.4kB README.md   
npm notice 622B  index.d.ts  
npm notice === Tarball Details === 
npm notice name:          gulp-brotli                             
npm notice version:       2.0.0                                   
npm notice package size:  4.2 kB                                  
npm notice unpacked size: 13.3 kB                                 
npm notice shasum:        b97dd72e4602dc4799c0df183795eede3d7214c5
npm notice integrity:     sha512-C/OYXFyoyZJr3[...]OUuAM1d1cDsHg==
npm notice total files:   6 
+ gulp-brotli@2.0.0
```

:tada:

**Comment by nstepien** [comment]
🎉 Great!
